<?php
/**
 * Created by PhpStorm.
 * User: kim6515516
 * Date: 2022-09-12
 * Time: 21:08
 */

namespace Tests\Unit\Services;


use App\Models\User;
use App\Services\BoardService;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

/**
 * 비지니스 로직을 검증하는 테스트코드를 작성한다.
 */

class BoardServiceTest extends TestCase
{
    use RefreshDatabase;
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testStore()
    {
        // Given
        $mockUser = User::create([
            'name' => 'mockUser',
            'email' => 'aaa@aaa.com',
            'password' => 'password'
        ]);

        $params = [
            "title" => "postTitle",
            "content" => "PostContent",
            "user_id" => $mockUser->id
        ];

        // When
        $service = new BoardService();
        $result = $service->store($params);

        // Then
        $this->assertNull($result);
        $this->assertDatabaseHas('boards', ['title' => 'postTitle']);
    }
}
